# Generated by Django 2.0.7 on 2018-08-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='message_text',
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='inbox.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='Sem assunto', max_length=100, verbose_name='Assunto'),
        ),
    ]
