# Generated by Django 2.0.7 on 2018-08-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_auto_20180803_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbox.Message'),
        ),
    ]
