# Generated by Django 2.0.7 on 2018-08-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_auto_20180803_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='not_view',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
    ]
