# Generated by Django 2.0.7 on 2018-11-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
    ]
