# Generated by Django 2.0.7 on 2018-07-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salário Mínimo')),
                ('hours_theoretical', models.PositiveIntegerField(verbose_name='Horas teóricas')),
                ('hours_practical_simulator', models.PositiveIntegerField(verbose_name='Horas práticas no simulador')),
                ('hours_practical_vehicle', models.PositiveIntegerField(verbose_name='Horas práticas no veículo')),
            ],
        ),
    ]
