# Generated by Django 2.0.7 on 2018-07-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(default='', verbose_name='Apelido'),
            preserve_default=False,
        ),
    ]
