# Generated by Django 2.0.7 on 2018-07-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Apelido'),
        ),
    ]
