# Generated by Django 2.0.7 on 2018-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180722_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='begin_expedient',
            field=models.TimeField(default='07:00', verbose_name='Início do expediente'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='end_expedient',
            field=models.TimeField(default='18:00', verbose_name='Fim do expediente'),
        ),
    ]
