# Generated by Django 2.0.7 on 2018-07-23 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_employee_type_cnh'),
        ('process', '0011_practicalcourse_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulator', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Aula no simulador')),
                ('day', models.DateField(default=datetime.datetime.now, verbose_name='Dia')),
                ('begin_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee', verbose_name='Instrutor')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='Processo')),
            ],
        ),
    ]
