# Generated by Django 2.0.7 on 2018-07-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_auto_20180725_2004'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['day'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('process', 'day', 'begin_time')},
        ),
    ]
