# Generated by Django 2.0.7 on 2018-07-19 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_medical', models.BooleanField(default=False, verbose_name='Exame médico')),
                ('exam_psychological', models.BooleanField(default=False, verbose_name='Exame psicológico')),
                ('date_exam', models.DateField(default=None, verbose_name='Data do exame')),
                ('status', models.CharField(choices=[('nao iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='Iniciado', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Dia da aula')),
                ('start_time', models.DateTimeField(verbose_name='Hora do início')),
                ('end_time', models.DateTimeField(verbose_name='Hora do fim')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name_plural': 'Aulas práticas',
                'verbose_name': 'Aula prática',
            },
        ),
        migrations.CreateModel(
            name='PracticalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='Não iniciado', max_length=20, verbose_name='Status')),
                ('vehicle', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name_plural': 'Cursos práticos',
                'verbose_name': 'Curso prático',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cnh', models.CharField(choices=[('ACC', 'ACC'), ('A', 'A'), ('B', 'B'), ('AB', 'A/B'), ('C', 'C'), ('AC', 'A/C'), ('D', 'D'), ('AD', 'A/D'), ('E', 'E'), ('AE', 'A/E')], max_length=3, verbose_name='Tipo da CNH')),
                ('date_start', models.DateField(default=datetime.datetime.now, verbose_name='Início')),
                ('date_end', models.DateField(verbose_name='Fim')),
                ('status', models.CharField(choices=[('nao iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='Iniciado', max_length=20, verbose_name='Status')),
                ('exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Exam', verbose_name='Exames')),
                ('practical_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.PracticalCourse', verbose_name='Curso prático')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student', verbose_name='Aluno')),
            ],
            options={
                'ordering': ['-date_start'],
                'verbose_name_plural': 'Processos',
                'verbose_name': 'Processo',
            },
        ),
        migrations.CreateModel(
            name='TheoreticalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Dia da aula')),
                ('start_time', models.DateTimeField(verbose_name='Hora do início')),
                ('end_time', models.DateTimeField(verbose_name='Hora do fim')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name_plural': 'Aulas teóricas',
                'verbose_name': 'Aula teórica',
            },
        ),
        migrations.CreateModel(
            name='TheoreticalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='Não iniciado', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Cursos teóricos',
                'verbose_name': 'Curso teórico',
            },
        ),
        migrations.AddField(
            model_name='theoreticalclass',
            name='theoretical_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.TheoreticalCourse', verbose_name='Curso teórico'),
        ),
        migrations.AddField(
            model_name='process',
            name='theoretical_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.TheoreticalCourse', verbose_name='Curso teórico'),
        ),
        migrations.AddField(
            model_name='practicalclass',
            name='practical_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.PracticalCourse', verbose_name='Curso prático'),
        ),
    ]
