# Generated by Django 2.0.7 on 2018-07-26 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_medical', models.BooleanField(choices=[(True, 'Apto'), (False, 'Não apto')], default=False, verbose_name='Exame médico')),
                ('exam_psychological', models.BooleanField(choices=[(True, 'Apto'), (False, 'Não apto')], default=False, verbose_name='Exame psicológico')),
                ('date_exam', models.DateField(default=None, null=True, verbose_name='Data do exame')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='iniciado', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulator', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Aula de simulador')),
                ('day', models.DateField(default=datetime.datetime.now, verbose_name='Dia da aula')),
                ('begin_time', models.TimeField(choices=[(datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00')], verbose_name='Hora do início')),
                ('end_time', models.TimeField(choices=[(datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00')], verbose_name='Hora do fim')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Person', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name_plural': 'Aulas práticas',
                'verbose_name': 'Aula prática',
            },
        ),
        migrations.CreateModel(
            name='PracticalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20, verbose_name='Status')),
                ('total_hours', models.PositiveIntegerField(default=20, verbose_name='Horas práticas necessárias')),
            ],
            options={
                'verbose_name_plural': 'Cursos práticos',
                'verbose_name': 'Curso prático',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cnh', models.CharField(choices=[('ACC', 'ACC'), ('A', 'A'), ('B', 'B'), ('AB', 'A/B'), ('C', 'C'), ('AC', 'A/C'), ('D', 'D'), ('AD', 'A/D'), ('E', 'E'), ('AE', 'A/E')], max_length=3, verbose_name='Tipo da CNH')),
                ('begin_date', models.DateField(default=datetime.datetime.now, verbose_name='Início')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fim')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='iniciado', max_length=20, verbose_name='Status')),
                ('exams', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.Exam', verbose_name='Exames')),
                ('practical_course', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.PracticalCourse', verbose_name='Curso prático')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Person', verbose_name='Aluno')),
            ],
            options={
                'verbose_name_plural': 'Processos',
                'ordering': ['-begin_date'],
                'verbose_name': 'Processo',
            },
        ),
        migrations.CreateModel(
            name='TheoreticalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now, verbose_name='Dia da aula')),
                ('begin_time', models.TimeField(choices=[(datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00')], verbose_name='Hora do início')),
                ('end_time', models.TimeField(choices=[(datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00')], verbose_name='Hora do fim')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Person', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name_plural': 'Aulas teóricas',
                'verbose_name': 'Aula teórica',
            },
        ),
        migrations.CreateModel(
            name='TheoreticalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Cursos teóricos',
                'verbose_name': 'Curso teórico',
            },
        ),
        migrations.AddField(
            model_name='theoreticalclass',
            name='theoretical_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='process.TheoreticalCourse', verbose_name='Curso teórico'),
        ),
        migrations.AddField(
            model_name='process',
            name='theoretical_course',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.TheoreticalCourse', verbose_name='Curso teórico'),
        ),
        migrations.AddField(
            model_name='practicalclass',
            name='practical_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='process.PracticalCourse', verbose_name='Curso prático'),
        ),
        migrations.AddField(
            model_name='practicalclass',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Vehicle', verbose_name='Veículo'),
        ),
    ]
