# Generated by Django 2.0.7 on 2018-07-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='date_end',
            field=models.DateField(blank=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='process',
            name='exams',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='process.Exam', verbose_name='Exames'),
        ),
        migrations.AlterField(
            model_name='process',
            name='practical_course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='process.PracticalCourse', verbose_name='Curso prático'),
        ),
        migrations.AlterField(
            model_name='process',
            name='theoretical_course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='process.TheoreticalCourse', verbose_name='Curso teórico'),
        ),
    ]
