# Generated by Django 2.0.7 on 2018-11-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20181101_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Person', verbose_name='Aluno'),
        ),
    ]
