# Generated by Django 2.0.7 on 2018-07-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20180719_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fim'),
        ),
    ]
