# Generated by Django 2.0.7 on 2018-07-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20180719_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date_exam',
            field=models.DateField(default=None, null=True, verbose_name='Data do exame'),
        ),
    ]
