# Generated by Django 2.0.7 on 2018-07-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20180719_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalclass',
            name='practical_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='process.PracticalCourse', verbose_name='Curso prático'),
        ),
        migrations.AlterField(
            model_name='theoreticalclass',
            name='theoretical_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='process.TheoreticalCourse', verbose_name='Curso teórico'),
        ),
    ]
