# Generated by Django 2.0.7 on 2018-07-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20180719_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalclass',
            name='simulator',
            field=models.BooleanField(default=False, verbose_name='Aula de simulador'),
        ),
    ]
