# Generated by Django 2.0.7 on 2018-07-21 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_practicalclass_simulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_medical',
            field=models.BooleanField(choices=[(True, 'Apto'), (False, 'Não apto')], default=False, verbose_name='Exame médico'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_psychological',
            field=models.BooleanField(choices=[(True, 'Apto'), (False, 'Não apto')], default=False, verbose_name='Exame psicológico'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='iniciado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='practicalcourse',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='iniciado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='theoreticalclass',
            name='day',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Dia da aula'),
        ),
        migrations.AlterField(
            model_name='theoreticalclass',
            name='end_time',
            field=models.TimeField(verbose_name='Hora do fim'),
        ),
        migrations.AlterField(
            model_name='theoreticalclass',
            name='start_time',
            field=models.TimeField(verbose_name='Hora do início'),
        ),
        migrations.AlterField(
            model_name='theoreticalcourse',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20, verbose_name='Status'),
        ),
    ]
