# Generated by Django 2.0.7 on 2018-07-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_auto_20180721_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalcourse',
            name='total_hours',
            field=models.PositiveIntegerField(default=20, verbose_name='Horas práticas necessárias'),
        ),
    ]
