# Generated by Django 2.0.7 on 2018-07-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_practicalcourse_total_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-begin_date'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.RenameField(
            model_name='practicalclass',
            old_name='start_time',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='date_start',
            new_name='begin_date',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='theoreticalclass',
            old_name='start_time',
            new_name='begin_time',
        ),
    ]
