# Generated by Django 2.0.7 on 2018-07-18 13:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('street', models.CharField(max_length=200, verbose_name='Rua')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PB', max_length=2, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Pessoa',
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Person')),
                ('function', models.CharField(choices=[('secretario', 'Secretário'), ('instrutor', 'Instrutor')], max_length=20, verbose_name='Função')),
                ('salary', models.DecimalField(decimal_places=2, default=950.0, max_digits=8, verbose_name='Salário')),
                ('registry', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('cnh', models.CharField(max_length=20, null=True, verbose_name='CNH')),
                ('type_cnh', models.CharField(choices=[('ACC', 'ACC'), ('A', 'A'), ('B', 'B'), ('AB', 'A/B'), ('C', 'C'), ('AC', 'A/C'), ('D', 'D'), ('AD', 'A/D'), ('E', 'E'), ('AE', 'A/E')], default='AB', max_length=3, null=True, verbose_name='Tipo da CNH')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Funcionários',
                'verbose_name': 'Funcionário',
            },
            bases=('accounts.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Person')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Alunos',
                'verbose_name': 'Aluno',
            },
            bases=('accounts.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
