# Generated by Django 2.0.7 on 2018-07-26 23:05

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('street', models.CharField(max_length=200, verbose_name='Rua')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PB', max_length=2, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('role_admin', models.BooleanField(default=False, verbose_name='Admin?')),
                ('role_secretary', models.BooleanField(default=False, verbose_name='Secretário?')),
                ('role_instructor', models.BooleanField(default=False, verbose_name='Instrutor?')),
                ('role_student', models.BooleanField(default=False, verbose_name='Aluno?')),
                ('current_view', models.CharField(blank=True, max_length=20, null=True, verbose_name='Visão atual')),
                ('registry', models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula')),
                ('salary', models.DecimalField(decimal_places=2, default=950.0, max_digits=8, verbose_name='Salário')),
                ('admission', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Admitido em')),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNH')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'ordering': ['name'],
                'verbose_name': 'Pessoa',
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
