# Generated by Django 2.0.7 on 2018-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Moto')], default='motorcycle', max_length=20, verbose_name='Tipo')),
                ('fabricator', models.CharField(max_length=20, verbose_name='Fabricante')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('plate', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('state', models.CharField(choices=[('funcionando', 'Funcionando'), ('em conserto', 'Em conserto')], default='funcionando', max_length=20, verbose_name='Estado')),
            ],
        ),
    ]
