# Generated by Django 2.0.7 on 2018-07-23 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='type_cnh',
        ),
    ]
